import React, { Fragment } from 'react';

import PortfolioCards from '../components/PortfolioCards/PortfolioCards';

const Project = () => {
  return (
    <Fragment>
      <div>
        <br />
        <br />
        <br />
      </div>
      <div className='section portfolio-section'>
        <div className='container space2'>
          <div className='row mb-5 justify-content-center'>
            <div className='col-md-8 text-center'>
              <br />
              <h1 className='mb-4 section-title'>Portfolio</h1>
              <h4 className='lead'>
                Below are some of the projects that I've been able to complete.
                Most of them use some form of Javascript, Html, and CSS. The
                bigger projects are all Full Stack, with aspects of React, API
                calls, and a backend database of some kind.
              </h4>
            </div>
          </div>
        </div>
        <div className='section'>
          <div className='container'>
            <div className='row'>
              <PortfolioCards
                image={
                  'https://images.pexels.com/photos/316681/pexels-photo-316681.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260'
                }
                title={'Code Hunters'}
                code={'MYSQL/Handlebars/Node/Express'}
                link1={'https://fast-stream-44549.herokuapp.com/'}
                link2={
                  'https://github.com/ucr-the-boyz/group-project-2.github.io'
                }
                description={
                  'Allows you to create a job listing that can be filtered basedon language and location.'
                }
              />
              <PortfolioCards
                image={
                  'https://images.pexels.com/photos/424184/pexels-photo-424184.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940'
                }
                title={'Employee Directory'}
                code={'HTML/Javascript/React/Express'}
                link1={'https://morning-everglades-79536.herokuapp.com/'}
                link2={'https://github.com/dglassick/budget-tracker.github.io'}
                description={
                  'React application that allows a user to filter through a list of employees generated by an API call.'
                }
              />
              <PortfolioCards
                image={
                  'https://images.pexels.com/photos/747113/pexels-photo-747113.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940'
                }
                title={'Budget Tracker'}
                code={'HTML/CSS/Javascript/IndexDB/PWA'}
                link1={'https://morning-everglades-79536.herokuapp.com/'}
                link2={'https://github.com/dglassick/budget-tracker.github.io'}
                description={
                  'Progressive Web App that used IndexedDB has functionality offline.'
                }
              />
            </div>
            <br></br>
            <br></br>
            <div className='row'>
              <PortfolioCards
                image={
                  'https://images.pexels.com/photos/209969/pexels-photo-209969.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'
                }
                title={'Workout Tracker'}
                code={'MongoDB/HTML/Node/Express/Routes'}
                link1={'https://pure-wildwood-89866.herokuapp.com/'}
                link2={'https://github.com/dglassick/workout-tracker.github.io'}
                description={
                  'Allows you to track your workouts and see graphs displayed.'
                }
              />
              <PortfolioCards
                image={
                  'https://images.pexels.com/photos/1108117/pexels-photo-1108117.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940'
                }
                title={'Burger App'}
                code={'Node/Express/MySQL/Jquery/Javascript'}
                link1={'https://stark-mountain-62873.herokuapp.com/'}
                link2={'https://github.com/dglassick/burger.github.io'}
                description={
                  'Application that saves the type of burger you want and then lets you switch an attribute to true.'
                }
              />
              <PortfolioCards
                image={
                  'https://images.pexels.com/photos/3507989/pexels-photo-3507989.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940'
                }
                title={'Note Taker'}
                code={'Node/Express/Javascript/Jquery'}
                link1={'https://thawing-falls-68929.herokuapp.com/'}
                link2={'https://github.com/dglassick/noteTaker.github.io'}
                description={
                  'Using JSON allows you create, edit, save, and delete notes that you have taken.'
                }
              />
            </div>
          </div>
        </div>
      </div>
      <br></br>
      <br></br>
    </Fragment>
  );
};

export default Project;
